// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaujlyklcwnebzyqpqqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdWpseWtsY3duZWJ6eXFwcXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODU3ODcsImV4cCI6MjA2OTU2MTc4N30.cjBOHdrGPMgx5o8Pc8oBJwxSt1a3iWCh44AkAf-jGIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});